changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - allcontributors
  categories:
    - title: ":boom: Breaking changes"
      labels:
        - semver-major
    - title: New Languages
      labels:
        - new-language
    - title: New Features
      labels:
        - semver-minor
    - title: Fixes
      labels:
        - semver-patch
        - bug
    - title: ":jack_o_lantern: Hacktoberfest Contributions"
      labels:
        - hacktoberfest
        - hacktoberfest-accepted
    - title: Other Changes
      labels:
        - "*"
